### ISSUE TITLE
Store browsing by departments

### ISSUE THREAD

**Issue by azubieta** [nomad-shell/nx-software-center#5]
Allow to explore the store contents by departments.

**Comment by azubieta** [comment]
@UriHerrera these are the sections that are currently registered at the ubuntu store
social-networking
 travel-local
reference
food-drink
 communication
 accessories
weather
 personalisation
education
productivity
 universal-accessaccessibility
entertainment
sports
developer-tools
 music-audio
shopping
finance
business
media-video
health-fitness
news-magazines
graphics
lifestyle
medical
science-engineering
games
 books-comics

**Comment by UriHerrera** [comment]
Working on it.

**Comment by azubieta** [comment]
Done, just the backgrounds are missing.

**Comment by azubieta** [comment]
Done
